name: "Basic Template definition"
app_type: flask
app_name: simple_application
components:
    html:
        index:
            type: html
            title: Simple html page.
    app:
        filename: app.py
        hostname: '0.0.0.0'
        port: 5000
        debug: True
        routes:
            - index:
                methods: ["GET", "POST"]
                render: index


        
