name: "Basic Template definition"
app_type: flask
app_name: simple_application
components:
    html:
        index:
            type: html
            title: Simple html page.
            scripts:
                - bootstrap:
                    path: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                - testscript:
                    path: "this is a test"
            components:
                basic: >
                    This is a test string. As long as this is there 
                    we are ok.
    app:
        filename: app.py
        hostname: '0.0.0.0'
        port: 5000
        debug: True
        routes:
            index:
                uri: "/"
                methods: ["GET", "POST"]
                view_filename: 'index.html'


        
