name: "Basic Template definition"
app_type: flask
app_name: simple_application
components:
    box1:
        loc:
            row: 0
            column: 0
            column_size: 12
        type: string
    box2:
        loc:
            row: 1
            column: 0
            column_size: 3
        type: strings




